import "./globals.css";

import { Inter } from "next/font/google";
import "bulma/css/bulma.min.css";
import Provider from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BD-Util",
  description: "Generated by Connor Baltich",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html >
  );
}
